import { Note, UserProfile, TeamActivity } from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'usr-1',
  fullName: 'Dũng Vũ',
  email: 'dung.vu@tasknest.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const MOCK_USERS: UserProfile[] = [
  CURRENT_USER,
  {
    id: 'usr-2',
    fullName: 'Hoàng Nguyễn',
    email: 'hoang.n@tasknest.io',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-3',
    fullName: 'Minh Trần',
    email: 'minh.t@tasknest.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-4',
    fullName: 'Phương Lê',
    email: 'phuong.l@tasknest.io',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-5',
    fullName: 'Tuấn Đặng',
    email: 'tuan.d@tasknest.io',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const MOCK_NOTES: Note[] = [
  {
    id: 'note-1',
    title: 'Kế hoạch Chiến lược Tính năng & Roadmap Quý 3',
    content: 'Đánh giá các mục tiêu trọng tâm Q3: Triển khai đồng bộ dữ liệu thời gian thực, hoàn thiện giao diện phân quyền nhóm và tối ưu chế độ ngoại tuyến.',
    isPrivate: false,
    status: 'in_progress',
    priority: 'P1',
    dueDate: '2026-08-05',
    tags: ['Sản phẩm', 'Chiến lược', 'Q3'],
    owner: CURRENT_USER,
    members: [
      { user: CURRENT_USER, permission: 'owner', status: 'accepted' },
      { user: MOCK_USERS[1], permission: 'edit', status: 'accepted' },
      { user: MOCK_USERS[2], permission: 'view', status: 'accepted' },
    ],
    checklist: [
      { id: 'c1', text: 'Chốt cấu trúc cơ sở dữ liệu Supabase RLS cho phân quyền note', completed: true },
      { id: 'c2', text: 'Tham khảo mẫu thiết kế UI/UX từ Linear & Raycast', completed: true },
      { id: 'c3', text: 'Tổ chức buổi Demo chạy thử với 5 thành viên nhóm', completed: false },
    ],
    pinned: true,
    createdAt: '2026-07-28T09:00:00Z',
    updatedAt: '2026-07-31T10:30:00Z',
  },
  {
    id: 'note-2',
    title: 'Mục tiêu Cá nhân Tuần này & Quản lý Tài chính',
    content: 'Theo dõi tiến độ học tập cá nhân: Thành thạo các tính năng React 19, lập bảng tính ngân sách cá nhân hàng tháng và kiểm tra sức khỏe định kỳ.',
    isPrivate: true,
    status: 'todo',
    priority: 'P2',
    dueDate: '2026-08-02',
    tags: ['Cá nhân', 'Mục tiêu'],
    owner: CURRENT_USER,
    members: [{ user: CURRENT_USER, permission: 'owner', status: 'accepted' }],
    checklist: [
      { id: 'c4', text: 'Rà soát hạn mức tiết kiệm hàng tháng', completed: false },
      { id: 'c5', text: 'Đọc chương 3 đến chương 5 sách Clean Code', completed: true },
    ],
    pinned: true,
    createdAt: '2026-07-30T14:15:00Z',
    updatedAt: '2026-07-30T14:15:00Z',
  },
  {
    id: 'note-3',
    title: 'Cập nhật Hệ thống Design Tokens & Giao diện UI',
    content: 'Thống nhất bảng màu Design Tokens theo phong cách Editorial Tactile Dark. Sử dụng nền Obsidian (#0B0F17) và màu Indigo (#6366F1) cho các trạng thái hoạt động.',
    isPrivate: false,
    status: 'completed',
    priority: 'P2',
    dueDate: '2026-07-31',
    tags: ['Thiết kế', 'UI/UX'],
    owner: MOCK_USERS[1],
    members: [
      { user: MOCK_USERS[1], permission: 'owner', status: 'accepted' },
      { user: CURRENT_USER, permission: 'edit', status: 'accepted' },
    ],
    checklist: [
      { id: 'c6', text: 'Định nghĩa biến màu sắc CSS HSL', completed: true },
      { id: 'c7', text: 'Tạo các component nguyên tử Button & Badge', completed: true },
    ],
    pinned: false,
    createdAt: '2026-07-25T11:00:00Z',
    updatedAt: '2026-07-31T08:20:00Z',
  },
  {
    id: 'note-4',
    title: 'Nhật ký Ý tưởng: Dự án Phụ tiếp theo',
    content: 'Nghiên cứu công cụ tự động sinh mã nguồn TypeScript cho ứng dụng Microservices.',
    isPrivate: true,
    status: 'todo',
    priority: 'P3',
    tags: ['Ý tưởng', 'Bản nháp'],
    owner: CURRENT_USER,
    members: [{ user: CURRENT_USER, permission: 'owner', status: 'accepted' }],
    checklist: [],
    pinned: false,
    createdAt: '2026-07-29T18:40:00Z',
    updatedAt: '2026-07-29T18:40:00Z',
  },
  {
    id: 'note-5',
    title: 'Rà soát Bảo mật Supabase & Chính sách RLS',
    content: 'Rà soát kỹ lưỡng các chính sách bảo mật phân quyền Row Level Security (RLS) trên các bảng profiles, notes, và note_members.',
    isPrivate: false,
    status: 'in_progress',
    priority: 'P1',
    dueDate: '2026-08-08',
    tags: ['Bảo mật', 'Cơ sở dữ liệu'],
    owner: CURRENT_USER,
    members: [
      { user: CURRENT_USER, permission: 'owner', status: 'accepted' },
      { user: MOCK_USERS[3], permission: 'edit', status: 'accepted' },
    ],
    checklist: [
      { id: 'c8', text: 'Viết test kiểm thử phân quyền RLS', completed: false },
      { id: 'c9', text: 'Xác nhận truy vấn SELECT cách ly note riêng tư', completed: true },
    ],
    pinned: false,
    createdAt: '2026-07-31T09:10:00Z',
    updatedAt: '2026-07-31T11:00:00Z',
  },
];

export const MOCK_ACTIVITIES: TeamActivity[] = [
  {
    id: 'act-1',
    user: MOCK_USERS[1],
    action: 'đã cập nhật danh sách công việc trong',
    noteTitle: 'Kế hoạch Chiến lược Tính năng & Roadmap Quý 3',
    timestamp: '10 phút trước',
  },
  {
    id: 'act-2',
    user: MOCK_USERS[2],
    action: 'đã tham gia với quyền xem trong',
    noteTitle: 'Rà soát Bảo mật Supabase & Chính sách RLS',
    timestamp: '1 giờ trước',
  },
  {
    id: 'act-3',
    user: CURRENT_USER,
    action: 'đã tạo ghi chú chung mới',
    noteTitle: 'Cập nhật Hệ thống Design Tokens & Giao diện UI',
    timestamp: '3 giờ trước',
  },
];
